# Generated by Django 3.1.1 on 2020-10-01 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('iso', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('secret_api_key', models.CharField(max_length=200)),
                ('public_api_key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('balance', models.FloatField()),
                ('available', models.FloatField()),
                ('in_orders', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.coin')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.FloatField()),
                ('taker', models.FloatField()),
                ('base_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_coin', to='panel.coin')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.exchange')),
                ('quote_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_coin', to='panel.coin')),
            ],
        ),
    ]
